### ISSUE TITLE
Shocking

### ISSUE THREAD

**Issue by markterluun** [EMart86/SwiftTickerView#1]
The first one or two items scroll smoothly but after that, the scrolling is not very smooth

**Comment by EMart86** [comment]
I did a research on that and i'm pretty sure, i can narrow it down to the separators. I'll keep you in touch.

**Comment by markterluun** [comment]
I noticed you updated to 1.1.0, solving this issue. Stuttering reduced significantly! Thanks :)

**Comment by fahlout** [comment]
I noticed still quite a bit of stutter when I'm using it.

**Comment by markterluun** [comment]
Are you running it in the simulator or on a device? I noticed a difference in performance

**Comment by fahlout** [comment]
I’m running it on device (iPhone 7 Plus and iPhone X)
