### ISSUE TITLE
Dynamic width custom view

### ISSUE THREAD

**Issue by SohaibSdq** [EMart86/SwiftTickerView#10]
Hello, 
I want to use a custom view that should have dynamic width as per the content. the custom view will contain a title label and badge label.
TIA

**Comment by EMart86** [comment]
Hi, is this what you are looking for?

let label = tickerView.dequeReusableNodeView(for: labelIdentifier) as? UILabel {
            label.text = text
            **label.sizeToFit()**
            label.textColor = .white
            return (label, reuseIdentifier: labelIdentifier)
