### ISSUE TITLE
Extra Distance Between the Nodes

### ISSUE THREAD

**Issue by SohaibSdq** [EMart86/SwiftTickerView#11]
I have registered a view and adjusted the width of the view as per the label in it, but the problem is I'm facing the issue of extra margin between the views.

**Comment by EMart86** [comment]
Hi, which problems are you facing?
Assigning distanceBetweenNodes should do the trick :)

**Comment by EMart86** [comment]
Like this 
tickerView.distanceBetweenNodes = 10 // any CGFloat value. Default is 8
Or if you don't want any extra margins, use .distanceBetweenNodes = 0
