### ISSUE TITLE
Frame width not obeyed

### ISSUE THREAD

**Issue by icompas** [EMart86/SwiftTickerView#12]
XCode 15 compiled.

The frame width is not obeyed anymore.
The ticker is defined with the same width like the logo below, but as you can see, the text is scrolling beyond the borders.

https://github.com/EMart86/SwiftTickerView/assets/44095390/49f2168c-2ab3-4396-bec9-5278032dcd40

**Comment by EMart86** [comment]
Hi and thank you for using this library.
What i understand from your description is, that you would like the SwiftTickerView to respect the full length of the screen, right?
If so, why don't you use either the bounds of the screen or the superview without margin?

**Comment by icompas** [comment]
Hi,
thanks for your reply. No, just the other way around. The frame of the text is scrolling across the left and right edge of the defined frame. But actually, the ticker has a width exactly matching the one of the icon view below.
Attached a clip which shows the behavior of the ticker before it gets compiled with the current version of XCode.

Hope that helps to understand.


https://github.com/EMart86/SwiftTickerView/assets/44095390/e66f9348-c0f6-46c2-947b-41dc1f1159e3

**Comment by EMart86** [comment]
Is the tickerViews clipsToBounds set to true?

**Comment by icompas** [comment]
Got it! That did the trick. Thank you! 👍
