### ISSUE TITLE
Leading separator

### ISSUE THREAD

**Issue by fahlout** [EMart86/SwiftTickerView#3]
I think this library will help me out tremendously. I was just wondering if there is any way to not show the separator view at the beginning when the text first starts scrolling.

Another less important thing: Is there any way to have the text start filling the view right away instead of slowly moving on screen until it fills up with text?

Thanks!

**Comment by EMart86** [comment]
👍 I'll try to come up with a more general solution. I'm glad when this ticker view helps you :)

**Comment by EMart86** [comment]
A quick approach for the initial offset (as a right to left ticker scrolling behavior) would be:

```
let customRenderer = Renderer(initial: { current, last, tickerView, offset in
            var frame = current.frame
            if let last = last {
                frame.origin.x = last.frame.maxX + offset
            } else {
                frame.origin.x = offset //or use 0 so that the ticker starts directly from the left border 
            }
            frame.origin.y = (tickerView.frame.height - frame.height) / 2
            return frame
        }, update: { current, offset in
            var frame = current.frame
            frame.origin.x -= offset
            return frame
        }, shouldAddNewNode: { current, tickerView, offset in
            tickerView.frame.width - current.frame.maxX > offset
        }, shouldRemoveNode: { current, _ in
            current.frame.maxX < 0
        })
```

but to be honest, this looks really hacky. I'm working on this and I will come up with a better solution. Best

**Comment by fahlout** [comment]
Thanks! I'm also unable to create the custom renderer in my view controller where I set up the ticker view as it's a open class within a final class in your code, so it says "Use of unresolved identifier 'Renderer'"

Edit: It's because the initializer for renderer is not public as well as the parameters in the init

**Comment by EMart86** [comment]
Hi, thx, i fixed in in the current dev branch and will release it tonight. Afterwards i'll give you further detail about the solution. Best

**Comment by EMart86** [comment]
Hi, sorry that it took that long.
I've just updated to the latest version 1.4.0.
To remove the first separator, call `tickerView.add(decorator: .ignoreFirstSeparator)`
To start from the leftBorder, call `tickerView.render = Renderer.rightToLeft.customize(with: SwiftTickerItemDecorators.prepareAtLeftInnerBorder())`
