### ISSUE TITLE
Update content

### ISSUE THREAD

**Issue by fahlout** [EMart86/SwiftTickerView#4]
Is there any way to update the content and restart the ticker view from the beginning? I have content that updates and am wondering how to accomplish that.

**Comment by EMart86** [comment]
Hi, sorry that it took that long. 
I've just implemented it in 1.4.0.
After providing a new content through the `SwiftTickerProviderProtocol` protocol, call `tickerView.reloadData()`, but it's gonna look broken as i mentioned it in the method comments. I'm open for any better suggestions for the reloading, eg fading or so. Best regards

**Comment by fahlout** [comment]
I have noticed a significant delay from the time I call `reloadData()` to the time the ticker actually starts moving again with the new data. It takes several seconds.

I'm using the ticker with the right to left renderer without customization as of right now.
